CREATE DATABASE telegram_images;
USE telegram_images;

CREATE TABLE Images (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FileId VARCHAR(255) NOT NULL,
    FilePath VARCHAR(500),
    UploadedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Tags (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE ImageTags (
    ImageId INT,
    TagId INT,
    PRIMARY KEY (ImageId, TagId),
    FOREIGN KEY (ImageId) REFERENCES Images(Id) ON DELETE CASCADE,
    FOREIGN KEY (TagId) REFERENCES Tags(Id) ON DELETE CASCADE
);